### ISSUE TITLE
Specify multiple subdomains with env variable

### ISSUE THREAD

**Issue by cholcombe973** [nickjer/namecheap-ddns#3]
Hello! Thank you for building this crate! It's been super useful for me. I had a question though about how to specify multiple subdomains when using the systemd timer format for calling the binary. I've tried various iterations of `NAMECHEAP_DDNS_SUBDOMAIN=@ www` or `NAMECHEAP_DDNS_SUBDOMAIN="@ www"` or `NAMECHEAP_DDNS_SUBDOMAIN="@,www"` however it fails on all of them. I saw this crate uses clap for parsing of the env variable. I wonder if clap has a bug where it can't accept comma separated values to the env variable. I'm likely doing something wrong. Could you steer me in the right direction? :)

Update: I tried producing a minimum program with just clap to see if I could reproduce this. It seems clap won't automatically separate env arguments that are comma separated. It sees them as a single value. If you'd like I can open a bug with clap to see if they can resolve this.

**Comment by nickjer** [comment]
Seems I needed to use this...

https://docs.rs/clap/latest/clap/struct.Arg.html#method.use_value_delimiter

in order for it to parse a comma delimited env var correctly. Publishing the new version 0.2.1, let me know if this resolves your issue.

**Comment by cholcombe973** [comment]
Yeah I just figured it out as well. I was going to PR you but you beat me to it :). I'll pull it down and let you know in a minute if it works

**Comment by cholcombe973** [comment]
Yup that fixed it! Thanks
