### ISSUE TITLE
Service fails upon reboot

### ISSUE THREAD

**Issue by ComicIvans** [nickjer/namecheap-ddns#4]
I have a systemd service and timer configured as the repository says. When rebooting the server, the `ddns-update` fails. These are the logs from `journalctl`:
```
-- Boot 25cb1618eeec4408b63b8d03e82f99ee --
ene 26 11:56:19 server namecheap-ddns[1396]: Error: Failed to update www.wupp.dev
ene 26 11:56:19 server namecheap-ddns[1396]: Caused by:
ene 26 11:56:19 server namecheap-ddns[1396]:     0: failed to lookup address information: Name or service not known
ene 26 11:56:19 server namecheap-ddns[1396]:     1: failed to lookup address information: Name or service not known
ene 26 11:56:19 server systemd[1]: Started Update DDNS records for Namecheap.
ene 26 11:56:19 server systemd[1]: ddns-update.service: Main process exited, code=exited, status=1/FAILURE
ene 26 11:56:19 server systemd[1]: ddns-update.service: Failed with result 'exit-code'.
```

The service works fine when restarted manually.

**Comment by nickjer** [comment]
Unfortunately I am not a systemd expert, but it sounds like it is attempting to start the `namecheap-ddns` service before your network is fully loaded.

```
# /etc/systemd/system/ddns-update.service

[Unit]
Description=Update DDNS records for Namecheap
After=network-online.target

# ...
```

:point_up: the line `After=network-online.target` should have addressed this. I wonder if something has changed recently.

**Comment by ComicIvans** [comment]
> Unfortunately I am not a systemd expert, but it sounds like it is attempting to start the `namecheap-ddns` service before your network is fully loaded.
> 
> ```desktop
> # /etc/systemd/system/ddns-update.service
> 
> [Unit]
> Description=Update DDNS records for Namecheap
> After=network-online.target
> 
> # ...
> ```
> 
> ☝️ the line `After=network-online.target` should have addressed this. I wonder if something has changed recently.
> 
> UPDATE: Ok after reading this...
> 
> https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
> 
> What happens if you add the `Wants=network-online.target`, i.e.,
> 
> ```desktop
> # /etc/systemd/system/ddns-update.service
> 
> [Unit]
> Description=Update DDNS records for Namecheap
> After=network-online.target
> Wants=network-online.target
> 
> # ...
> ```

Solved after changing `network-online.target` to `nss-user-lookup.target` like this:
```desktop
# /etc/systemd/system/ddns-update.service

[Unit]
Description=Update DDNS records for Namecheap
After=nss-user-lookup.target
Wants=nss-user-lookup.target

# ...
```

**Comment by nickjer** [comment]
Interesting. I wonder if we need a name resolver up and running.
